### ISSUE TITLE
IC1 : VCCUV and OVLO are connected together

### ISSUE THREAD

**Issue by Jmanhes** [thomasfla/power-board#1]
- Disconnect VCCUV and OVLO
- Leave VCCUV open (undervoltage lockout set to 7) or set resistors bridge according your needs.
- Set OVLO to GND (disable over voltage lockout) or set resistors bridge according your needs.

**Comment by Jmanhes** [comment]
- Disconnect VCCUV and OVLO
   - Leave VCCUV open (undervoltage lockout set to 7) or set resistors bridge according your needs.
   - Set OVLO to GND (disable over voltage lockout) or set resistors bridge according your needs.

**Comment by thomasfla** [comment]
Thanks
